GREEN        := $(shell tput -Txterm setaf 2)
RESET        := $(shell tput -Txterm sgr0)

TARGET := x86_64-elf
CC := $(TARGET)-gcc
AS := $(TARGET)-as
LD := $(TARGET)-ld


CFLAGS := -ffreestanding -O2 -Wall -Wextra -Iinclude -g




